# Generated by Django 5.0.3 on 2024-05-02 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Book_Rent', '0004_alter_sell_model_auth_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sell_model',
            old_name='auth_id',
            new_name='uploaded_by',
        ),
    ]
