# Generated by Django 5.0.3 on 2024-05-02 15:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Book_Rent', '0007_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='sell_model',
            name='cat',
            field=models.ForeignKey(default=7, on_delete=django.db.models.deletion.CASCADE, to='Book_Rent.category'),
        ),
    ]
