# Generated by Django 5.0.3 on 2024-05-16 12:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Book_Rent', '0009_rename_cat_sell_model_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sell_model',
            name='price',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
